# screen parameteres
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOUR = "black"

# default length of a turtle object
BASE_TURTLE_LENGTH = 21

# paddle parameters
PADDLE_COLOUR = "white"
PADDLE_STRETCH_LENGTH = 6
PADDLE_WIDTH = BASE_TURTLE_LENGTH
PADDLE_LENGTH = BASE_TURTLE_LENGTH * PADDLE_STRETCH_LENGTH
PADDLE_DISTANCE_FROM_SCREEN_BOTTOM = 50
PADDLE_STARTING_X_POSITION = 0
PADDLE_Y_POSITION = SCREEN_HEIGHT // -2 + PADDLE_DISTANCE_FROM_SCREEN_BOTTOM
PADDLE_MOVE_DISTANCE = 15

# ball parameters
BALL_COLOUR = "white"
BALL_STARTING_X_POSITION = PADDLE_STARTING_X_POSITION
BALL_STARTING_Y_POSITION = PADDLE_Y_POSITION + BASE_TURTLE_LENGTH
BALL_SPEED = 0.02
BALL_MOVE_DISTANCE = 5
BALL_RADIUS = BASE_TURTLE_LENGTH / 2

# brick parameters
BRICK_STRETCH_LENGTH = 4
BRICK_WIDTH = BASE_TURTLE_LENGTH
BRICK_LENGTH = BASE_TURTLE_LENGTH * BRICK_STRETCH_LENGTH

# brick factory parameters
GAP_BETWEEN_BRICKS = 1
NUMBER_OF_ROWS = 8
NUMBER_OF_BRICKS_PER_ROW = SCREEN_WIDTH // (
    BASE_TURTLE_LENGTH * BRICK_STRETCH_LENGTH + GAP_BETWEEN_BRICKS
)
BRICKS_STARTING_X_POSITION = -SCREEN_WIDTH // 2
BRICKS_STARTING_Y_POSITION = 75

# scoreboard parameters
LIVES = 3
SCORE_DISTANCE_FROM_TOP = 35
SCORE_X_POSITION = 0
SCORE_Y_POSITION = SCREEN_HEIGHT // 2 - SCORE_DISTANCE_FROM_TOP
FONT = ("Arial", 20, "normal")
